apiVersion: solution.symphony/v1
kind: Solution
metadata: 
  name: sample-visualization-solution
spec:  
  metadata:
    deployment.replicas: "#1"
    service.ports: "[{\"name\":\"port9090\",\"port\": 9090}]"
    service.type: "LoadBalancer"
  components:
  - name: sample-visualization-solution
    type: container
    properties:
      container.ports: "[{\"containerPort\":9090,\"protocol\":\"TCP\"}]"
      container.imagePullPolicy: "Always"
      container.resources: "{\"requests\":{\"cpu\":\"100m\",\"memory\":\"100Mi\"}}"        
      container.image: "prom/prometheus"
    sidecars:
    - name: sample-visualization-sidecar
      type: container
      properties:
        container.image: "redis:latest"